server:
  port: 8040

spring:
  redis:
    host: 120.79.210.91
    port: 6379
    lettuce:
      pool:
        min-idle: 50
        max-idle: 256
        max-active: 1000
    database: 0
    timeout: 10s
  datasource:
    url: jdbc:mysql://120.79.210.91:3306/Test?useUnicode=true&characterEncoding=utf8&useSSL=false&zeroDateTimeBehavior=convertToNull
    password: 123456
    username: root
    driver-class-name: com.mysql.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      connection-test-query: SELECT 1 FROM DUAL
      idle-timeout: 60000
      connection-timeout: 60000
      validation-timeout: 3000
      login-timeout: 5
      max-lifetime: 60000

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    cache-enabled: true
    default-enum-type-handler: org.apache.ibatis.type.EnumOrdinalTypeHandler
    use-generated-keys: true